version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10.16.2-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - deps-{{ checksum "package.json" }}-{{ checksum
              "package-lock.json"}}
            - deps-{{ checksum "package.json" }}-
            - deps-
      # - run: sh circle_build_npmrc.sh
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key:
            deps-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
          paths:
            - ~/.npm
            - ~/.cache
      - run:
          name: Run tests
          command: npm run test
